[build]
  # Fixed command for Netlify build - we're now installing the specific Rollup native module needed
  command = "npm i @rollup/rollup-linux-x64-gnu && npm run build"
  publish = "dist"
  
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Make sure functions have access to necessary files
  included_files = ["netlify/functions/**", "shared/**"]
  
# Redirect API requests to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# For all other routes, serve the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  
[dev]
  framework = "vite"
  
# Important: Make sure functions are built properly
[build.environment]
  # Use Node.js 18.17.1 specifically for better compatibility
  NODE_VERSION = "18.17.1"
  # Ensure Linux architecture is properly detected
  NETLIFY_USE_YARN = "false"
  # We're installing the native module directly now, so we can let Rollup use it
  # NPM_FLAGS = "--legacy-peer-deps"